apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-pods
  name: nginx-pods
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-pods
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-pods
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
