- name: Gather the list of data to download
  hosts: all
  tasks:
  - name: create list of target datafiles
    ansible.builtin.shell: "mc ls ds4eng/britishlibrary | awk '{print $6}' > .targets"
    delegate_to: 127.0.0.1

- name: download the individual zip datafiles
  hosts: all
  vars:
    targets: "{{lookup('file','.targets')|split('\n')}}"
  tasks:
  - name: Create temp folder for incomplete downloads on larger volume
    ansible.builtin.file:
      path: data/tmp
      state: directory
      mode: '0755' 
  - name: Fetch the individual files 
    ansible.builtin.get_url:
      url:   "https://s3.ds4eng.condenser.arc.ucl.ac.uk/britishlibrary/{{ item }}"
      dest: data
      tmp_dest: data/tmp
    loop: "{{targets}}"
    register: monitor