- name: prepare pipeline
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: "Clone git repo"
    ansible.builtin.git:
      repo: "https://github.com/owainkenwayucl/coursework-c0235"
      dest: "/home/almalinux/coursework-c0235"
  - name: "Set up software"
    ansible.builtin.pip:
      name: /home/almalinux/coursework-c0235/lecture5b_dataengexample/dataeng
