- name: time how long it takes to analyse one file on each machine
  hosts: all
  vars:
    targets:
      - 1850-1859
  tasks:
  - name: Run the analysis on the target files, and time it
    ansible.builtin.shell: analyse data/{{item}}.zip arms
    register result
  - name: print the result when the playbook is run
    ansible.builtin.debug:
      var: result
