- name: Update packages and install minimum requirements.
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install epel
    ansible.builtin.dnf:
      name:
        - epel-release
      state: latest
  - name: Enable crb
    ansible.builtin.shell: dnf config-manager --set-enabled crb
  - name: Install quality of life tools
    ansible.builtin.dnf:
      name:
        - vim
        - emacs
        - nano
        - screen
        - tmux
        - net-tools
        - bind-utils
        - htop
        - git
        - ansible
        - make
        - wget
        - links
        - unzip
      state: latest
  - name: Install Python 3
    ansible.builtin.dnf:
      name:
        - python3-devel
        - python3-pip
        - python3-virtualenv
      state: latest
  - name: Install compilers
    ansible.builtin.dnf:
      name:
      - g++
      - gfortran
      - openmpi-devel
      - openmpi
      - patch
      - bzip2
      - python3-mpi4py-openmpi
      - make
      state: latest
