- name: Set up second disk
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Partition disk
    community.general.parted:
      name: "data"
      device: "/dev/vdb"
      label: "gpt"
      number: 1
      state: present
      fs_type: xfs
  - name: Format disk
    community.general.filesystem:
      dev: "/dev/vdb1"
      fstype: "xfs"
      state: present
  - name: Make mount point
    ansible.builtin.file:
      path: /data
      state: directory
  - name: XFS mount
    ansible.posix.mount:
      boot: true
      state: mounted
      fstype: xfs
      src: "/dev/vdb1"
      path: /data
      opts: defaults
  - name: Make user directory
    ansible.builtin.file:
      path: /data/almalinux
      state: directory
      owner: almalinux
  - name: Link in home directory
    ansible.builtin.file:
      dest: /home/almalinux/data
      state: link
      src: /data/almalinux
      owner: almalinux
